name: Generate docs
on: 
  push:
    branches: [master]
jobs:
  Start:
    
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
      - name: Install dependencies
        run: npm install
      - name: Generate new docs
        run: npm run docsgen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Genrated docs
